-- DML for m_spell_source_book
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Acid Splash', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blade Ward', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Booming Blade', 'SCAG');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Booming Blade', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Chill Touch', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Control Flames', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Control Flames', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Create Bonfire', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Create Bonfire', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dancing Lights', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Druidcraft', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Eldritch Blast', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Encode Thoughts', 'GGtR');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fire Bolt', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Friends', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Frostbite', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Frostbite', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Green-Flame Blade', 'SCAG');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Green-Flame Blade', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Guidance', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Gust', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Gust', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Infestation', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Light', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Lightning Lure', 'SCAG');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Lightning Lure', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mage Hand', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Magic Stone', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Magic Stone', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mending', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Message', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mind Sliver', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Minor Illusion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mold Earth', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mold Earth', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Poison Spray', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Prestidigitation', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Primal Savagery', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Produce Flame', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ray of Frost', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Resistance', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sacred Flame', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shape Water', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shillelagh', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shocking Grasp', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Spare the Dying', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sword Burst', 'SCAG');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sword Burst', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Thaumaturgy', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Thorn Whip', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Thunderclap', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Thunderclap', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Toll the Dead', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('True Strike', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Vicious Mockery', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Word of Radiance', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Absorb Elements', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Absorb Elements', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Alarm', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Animal Friendship', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Armor of Agathys', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Arms of Hadar', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Bane', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Beast Bond', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Beast Bond', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Bless', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Burning Hands', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Catapult', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Catapult', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Cause Fear', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ceremony', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Chaos Bolt', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Charm Person', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Chromatic Orb', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Color Spray', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Command', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Compelled Duel', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Comprehend Languages', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Create or Destroy Water', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Cure Wounds', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Detect Evil and Good', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Detect Magic', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Detect Poison and Disease', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Disguise Self', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dissonant Whispers', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Divine Favor', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Earth Tremor', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Earth Tremor', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ensnaring Strike', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Entangle', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Expeditious Retreat', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Faerie Fire', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('False Life', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Feather Fall', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Find Familiar', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fog Cloud', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Goodberry', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Grease', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Guiding Bolt', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hail of Thorns', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Healing Word', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hellish Rebuke', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Heroism', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hex', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hunter''s Mark', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ice Knife', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ice Knife', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Identify', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Illusory Script', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Inflict Wounds', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Jump', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Longstrider', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mage Armor', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Magic Missile', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Protection from Evil and Good', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Purify Food and Drink', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ray of Sickness', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sanctuary', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Searing Smite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shield', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shield of Faith', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Silent Image', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sleep', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Snare', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Speak with Animals', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tasha''s Caustic Brew', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tasha''s Hideous Laughter', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tenser''s Floating Disk', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Thunderous Smite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Thunderwave', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Unseen Servant', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Witch Bolt', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wrathful Smite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Zephyr Strike', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Aganazzar''s Scorcher', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Aganazzar''s Scorcher', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Aid', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Alter Self', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Animal Messenger', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Arcane Lock', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Augury', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Barkskin', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Beast Sense', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blindness/Deafness', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blur', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Branding Smite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Calm Emotions', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Cloud of Daggers', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Continual Flame', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Cordon of Arrows', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Crown of Madness', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Darkness', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Darkvision', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Detect Thoughts', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dragon''s Breath', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dust Devil', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dust Devil', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Earthbind', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Earthbind', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Enhance Ability', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Enlarge/Reduce', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Enthrall', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Find Steed', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Find Traps', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Flame Blade', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Flaming Sphere', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Flock of Familiars', 'LLK');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Gentle Repose', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Gust of Wind', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Healing Spirit', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Heat Metal', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hold Person', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Invisibility', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Knock', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Lesser Restoration', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Levitate', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Locate Animals or Plants', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Locate Object', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Magic Mouth', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Magic Weapon', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Maximilian''s Earthen Grasp', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Maximilian''s Earthen Grasp', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Melf''s Acid Arrow', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mind Spike', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mirror Image', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Misty Step', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Moonbeam', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Nystul''s Magic Aura', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Pass without Trace', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Phantasmal Force', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Prayer of Healing', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Protection from Poison', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Pyrotechnics', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Pyrotechnics', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ray of Enfeeblement', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Rope Trick', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Scorching Ray', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('See Invisibility', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shadow Blade', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shatter', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Silence', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Skywrite', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Skywrite', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Snilloc''s Snowball Swarm', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Snilloc''s Snowball Swarm', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Spider Climb', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Spike Growth', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Spiritual Weapon', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Suggestion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Beast', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tasha''s Mind Whip', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Warding Bond', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Warding Wind', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Warding Wind', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Web', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Zone of Truth', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Animate Dead', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Aura of Vitality', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Beacon of Hope', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Bestow Curse', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blinding Smite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blink', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Call Lightning', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Catnap', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Clairvoyance', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Animals', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Barrage', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Counterspell', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Create Food and Water', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Crusader''s Mantle', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Daylight', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dispel Magic', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Elemental Weapon', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Enemies Abound', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Erupting Earth', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Erupting Earth', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fear', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Feign Death', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fireball', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Flame Arrows', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Flame Arrows', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fly', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Galder''s Tower', 'LLK');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Gaseous Form', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Glyph of Warding', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Haste', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hunger of Hadar', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hypnotic Pattern', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Intellect Fortress', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Leomund''s Tiny Hut', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Life Transference', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Lightning Arrow', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Lightning Bolt', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Magic Circle', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Major Image', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mass Healing Word', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Meld into Stone', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Melf''s Minute Meteors', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Melf''s Minute Meteors', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Nondetection', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Phantom Steed', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Plant Growth', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Protection from Energy', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Remove Curse', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Revivify', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sending', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sleet Storm', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Slow', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Speak with Dead', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Speak with Plants', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Spirit Guardians', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Spirit Shroud', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Stinking Cloud', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Fey', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Lesser Demons', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Shadowspawn', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Undead', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Thunder Step', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tidal Wave', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tidal Wave', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tiny Servant', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tongues', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Vampiric Touch', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Sand', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Sand', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Water', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Water', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Water Breathing', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Water Walk', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wind Wall', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Arcane Eye', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Aura of Life', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Aura of Purity', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Banishment', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blight', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Charm Monster', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Compulsion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Confusion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Minor Elementals', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Woodland Beings', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Control Water', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Death Ward', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dimension Door', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Divination', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dominate Beast', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Elemental Bane', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Elemental Bane', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Evard''s Black Tentacles', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fabricate', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Find Greater Steed', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fire Shield', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Freedom of Movement', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Galder''s Speedy Courier', 'LLK');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Giant Insect', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Grasping Vine', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Greater Invisibility', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Guardian of Faith', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Guardian of Nature', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hallucinatory Terrain', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Ice Storm', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Leomund''s Secret Chest', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Locate Creature', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mordenkainen''s Faithful Hound', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mordenkainen''s Private Sanctum', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Otiluke''s Resilient Sphere', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Phantasmal Killer', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Polymorph', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shadow of Moil', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sickening Radiance', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Staggering Smite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Stone Shape', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Stoneskin', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Storm Sphere', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Storm Sphere', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Aberration', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Construct', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Elemental', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Greater Demon', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Vitriolic Sphere', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Vitriolic Sphere', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Fire', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Watery Sphere', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Watery Sphere', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Animate Objects', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Antilife Shell', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Awaken', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Banishing Smite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Bigby''s Hand', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Circle of Power', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Cloudkill', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Commune', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Commune with Nature', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Cone of Cold', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Elemental', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Volley', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Contact Other Plane', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Contagion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Control Winds', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Creation', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Danse Macabre', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dawn', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Destructive Wave', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dispel Evil and Good', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dominate Person', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dream', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Enervation', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Far Step', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Flame Strike', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Geas', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Greater Restoration', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hallow', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Hold Monster', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Holy Weapon', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Immolation', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Immolation', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Infernal Calling', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Insect Plague', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Legend Lore', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Maelstrom', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Maelstrom', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mass Cure Wounds', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mislead', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Modify Memory', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Negative Energy Flood', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Passwall', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Planar Binding', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Raise Dead', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Rary''s Telepathic Bond', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Reincarnate', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Scrying', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Seeming', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Skill Empowerment', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Steel Wind Strike', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Celestial', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Swift Quiver', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Synaptic Static', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Telekinesis', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Teleportation Circle', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Transmute Rock', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Transmute Rock', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tree Stride', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Force', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Light', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Stone', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wrath of Nature', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Arcane Gate', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blade Barrier', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Bones of the Earth', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Bones of the Earth', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Chain Lightning', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Circle of Death', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Fey', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Contingency', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Create Homunculus', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Create Undead', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Disintegrate', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Drawmij''s Instant Summons', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Druid Grove', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Eyebite', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Find the Path', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Flesh to Stone', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Forbiddance', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Globe of Invulnerability', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Guards and Wards', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Harm', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Heal', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Heroes'' Feast', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Flame', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Flame', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Ice', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Ice', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Stone', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Stone', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Wind', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Investiture of Wind', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Magic Jar', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mass Suggestion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mental Prison', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Move Earth', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Otiluke''s Freezing Sphere', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Otto''s Irresistible Dance', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Planar Ally', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Primordial Ward', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Primordial Ward', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Programmed Illusion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Scatter', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Soul Cage', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Summon Fiend', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sunbeam', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tasha''s Otherworldly Guise', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tenser''s Transformation', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Transport via Plants', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('True Seeing', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Ice', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wall of Thorns', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wind Walk', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Word of Recall', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Conjure Celestial', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Crown of Stars', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Delayed Blast Fireball', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Divine Word', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dream of the Blue Veil', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Etherealness', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Finger of Death', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Fire Storm', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Forcecage', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mirage Arcane', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mordenkainen''s Magnificent Mansion', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mordenkainen''s Sword', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Plane Shift', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Power Word Pain', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Prismatic Spray', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Project Image', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Regenerate', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Resurrection', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Reverse Gravity', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sequester', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Simulacrum', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Symbol', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Teleport', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Temple of the Gods', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Whirlwind', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Whirlwind', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Abi-Dalzim''s Horrid Wilting', 'EE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Abi-Dalzim''s Horrid Wilting', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Animal Shapes', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Antimagic Field', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Antipathy/Sympathy', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Clone', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Control Weather', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Demiplane', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Dominate Monster', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Earthquake', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Feeblemind', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Glibness', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Holy Aura', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Illusory Dragon', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Incendiary Cloud', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Maddening Darkness', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Maze', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mighty Fortress', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mind Blank', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Power Word Stun', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Sunburst', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Telepathy', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Tsunami', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Astral Projection', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Blade of Disaster', 'TCE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Foresight', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Gate', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Imprisonment', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Invulnerability', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mass Heal', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Mass Polymorph', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Meteor Swarm', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Power Word Heal', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Power Word Kill', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Prismatic Wall', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Psychic Scream', 'XGE');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Shapechange', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Storm of Vengeance', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Time Stop', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('True Polymorph', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('True Resurrection', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Weird', 'PHB');
INSERT INTO m_spell_source_book (spell_name, book_code) VALUES ('Wish', 'PHB');

COMMIT;